### ISSUE TITLE
At 'drawer_bloc.dart' when first adding the files

### ISSUE THREAD

**Issue by Lix-ai** [TechieBlossom/user_profile_and_drawer#2]
The superclass 'Bloc<DrawerEvents, DrawerStates>' doesn't have a zero argument constructor.  Try declaring a zero argument constructor in 'Bloc<DrawerEvents, DrawerStates>', or declaring a constructor in DrawerBloc that explicitly invokes a constructor in 'Bloc<DrawerEvents, DrawerStates>'.

**Comment by TechieBlossom** [comment]
Downgrade the bloc version.

**Comment by morrieinmaas** [comment]
Hey, I'm also just learning and following your tutorial. First of all thanks a bunch.

I think another way to go about this to replace:
```
 @override
 DrawerStates get initialState => UserProfileScreen();
```
with (as suggested by android-studio):
```
 DrawerBloc({@required DrawerStates initialState}) : super(initialState);

```
in drawer_bloc.dart.

You are then able to pass an initial state in main.dart by providing it as a parameter when you instantiate DrawerBloc like so:
```
 home: BlocProvider<DrawerBloc>(
          create: (context) => DrawerBloc(initialState: UserProfileScreen()),
            child: DrawerLayout()),
);
```

or you can use the version this project uses  flutter_bloc: ^2.1.1 (set that in pubspec.yaml). the current version i think is 6.1.1

**Comment by Lix-ai** [comment]
Thanks

**Comment by PrateekSharma1712** [comment]
Why I said to downgrade and why Android studio is suggesting you parameterized constructor is because in Bloc 6 and higher versions constructor is made parameterized.
